### ISSUE TITLE
How to launch testium on Linux?

### ISSUE THREAD

**Issue by machei** [groupon/testium#167]
hey guys, i have tried to use `config.app.port = 4444` and still doesn't work (but another error).

At first I will place error with using a default config:

```
machei@VirtualMachei-PC:~$ ./project/node_modules/.bin/testium --browser chrome
Preparing chrome...
/home/machei/project/node_modules/testium/lib/cli/console.js:114
      throw error;
            ^
Error: App not listening on 36020
    at /home/machei/project/node_modules/testium/lib/processes/application/index.js:92:23
    at /home/machei/project/node_modules/testium/lib/processes/port.js:45:12
    at Socket.<anonymous> (/home/machei/project/node_modules/testium/node_modules/portscanner/lib/portscanner.js:104:5)
    at Socket.emit (events.js:107:17)
    at TCP.close (net.js:485:12)
```
`machei@VirtualMachei-PC:~$ nodejs -v
v0.12.7`

**Comment by jkrems** [comment]
Sorry you're running into problems! Can you describe how you set the config? E.g. are you creating an `.testiumrc` file like this in `/home/machei/project`?

```ini
[app]
port = 4444
```

**Comment by machei** [comment]
very thank u, worked ;)
