### ISSUE TITLE
testium_launch env variable is not respected in v3.3.0

### ISSUE THREAD

**Issue by gprasant** [groupon/testium#180]
*Steps*: 
(This was tested on the deal page repo [funnel/deal])
1. run `make test-dev` in one terminal 
2. In another terminal , run `testium_launch=false mocha test/integration -g 'Whatever'`

You get an exception 

*stack trace*: 
```
  1) Wishlist button on Deal Page "before all" hook: injectBrowserHook:
     Error: Failed to initialize WebDriver. Check phantomjs.log.
Checking port 41998:
listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at Server.listen (net.js:1138:5)
    at Object.findOpen (node_modules/testium/node_modules/testium-core/node_modules/subprocess/lib/port.js:28:19)
    at node_modules/testium/node_modules/testium-core/node_modules/subprocess/lib/index.js:37:21
    at node_modules/testium/node_modules/testium-core/node_modules/subprocess/lib/log.js:24:16
    at OpenReq.Req.done (node_modules/graceful-fs/graceful-fs.js:143:5)
    at OpenReq.done (node_modules/graceful-fs/graceful-fs.js:63:22)
    at Object.oncomplete (fs.js:107:15)

```

**Comment by jkrems** [comment]
Next reinstall of testium should fix it!
