### ISSUE TITLE
selenium download fails with "TypeError('Path must be a string...)"

### ISSUE THREAD

**Issue by katylava** [groupon/testium#190]
```
> ./node_modules/.bin/testium --download-selenium

[testium] grabbing selenium standalone server 2.43.0
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received { url: 'http://selenium-release.storage.googleapis.com/2.43/selenium-server-standalone-2.43.0.jar',
  name: 'selenium_2.43.0.jar' }
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1357:5)
    at /Users/kyl/Code/Work/apps/redacted/src/node_modules/download/index.js:35:43
    at each (/Users/kyl/Code/Work/apps/redacted/src/node_modules/each-async/each-async.js:63:4)
    at module.exports (/Users/kyl/Code/Work/apps/redacted/src/node_modules/download/index.js:33:5)
    at module.exports (/Users/kyl/Code/Work/apps/redacted/src/node_modules/selenium-download/lib/download.js:58:12)
    at module.exports (/Users/kyl/Code/Work/apps/redacted/src/node_modules/selenium-download/lib/selenium/download.js:56:12)
    at /Users/kyl/Code/Work/apps/redacted/src/node_modules/selenium-download/lib/selenium/index.js:46:14
    at module.exports (/Users/kyl/Code/Work/apps/redacted/src/node_modules/selenium-download/lib/selenium/version.js:134:12)
    at /Users/kyl/Code/Work/apps/redacted/src/node_modules/selenium-download/lib/selenium/index.js:41:12
    at /Users/kyl/Code/Work/apps/redacted/src/node_modules/selenium-download/node_modules/async/lib/async.js:511:21
    at /Users/kyl/Code/Work/apps/redacted/src/node_modules/selenium-download/node_modules/async/lib/async.js:227:13
    at /Users/kyl/Code/Work/apps/redacted/src/node_modules/selenium-download/node_modules/async/lib/async.js:111:13
    at Array.forEach (native)
    at _each (/Users/kyl/Code/Work/apps/redacted/src/node_modules/selenium-download/node_modules/async/lib/async.js:32:24)
    at async.each (/Users/kyl/Code/Work/apps/redacted/src/node_modules/selenium-download/node_modules/async/lib/async.js:110:9)
    at _asyncMap (/Users/kyl/Code/Work/apps/redacted/src/node_modules/selenium-download/node_modules/async/lib/async.js:226:9)
    at Object.map (/Users/kyl/Code/Work/apps/redacted/src/node_modules/selenium-download/node_modules/async/lib/async.js:204:23)
    at _parallel (/Users/kyl/Code/Work/apps/redacted/src/node_modules/selenium-download/node_modules/async/lib/async.js:509:20)
    at Object.async.parallel (/Users/kyl/Code/Work/apps/redacted/src/node_modules/selenium-download/node_modules/async/lib/async.js:539:9)
    at ensure (/Users/kyl/Code/Work/apps/redacted/src/node_modules/selenium-download/lib/index.js:71:16)
    at Object.update (/Users/kyl/Code/Work/apps/redacted/src/node_modules/selenium-download/lib/index.js:76:10)
```

**Comment by jkrems** [comment]
Thanks for the report! I assume this was on node 6. This should be fixed now via `selenium-download@2.0.4`. Sorry for the delay. :)

**Comment by jkrems** [comment]
(Feel free to reopen if it still happens.)

**Comment by katylava** [comment]
Yes this works now. Thanks!
